name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
     
    - name: get Buffalo Framwork
      run: go get -u github.com/gobuffalo/buffalo/buffalo
      
    - name: get npm
      run: npm install
      
    - name: install copr-cli
      run: pip install copr-cli
      
    - name: build with buffalo
      run: buffalo build
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: write something into a file
      - run: test >> sometextfile.txt
      
      - name: read the document
      - run: cat sometextfile.txt
