# Altes Workflow File 
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: check if rpm works
        run: rpmbuild --help

      - name: Create the folder tree
        run: mkdir -p ~/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
      
      - name: check for path
        run: pwd
      
      - name: Copy all the source files into
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; cp -R * ~/rpmbuild/SOURCES

      - name: check for copie
        run: ls ~/rpmbuild/SOURCES

      - name: move .spec File to /SPECS
        run: mv /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/calculator.spec ~/rpmbuild/SPECS
      
      - name: check move
        run: ls ~/rpmbuild/SPECS
        
      - name: run rpmbuild
        run: rpmbuild -ba ~/rpmbuild/SPECS/calculator.spec
      
      - name: check 
        run: ls; tree
