# Altes Workflow File 
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_with_buffalo:
    name: build binary with Buffalo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'

      - name: get Buffalo Framwork
        run: cd rpmbuild/sourceCode; go get -u github.com/gobuffalo/buffalo/buffalo

      - name: Set up npm
        run: pip install npm
      
      - name: remove node_module and install it again
        run: cd rpmbuild/sourceCode;rm -rf node_modules; npm install
              
      - name: remove old CalcBuffaloBinary
        run: rm CalcBuffaloBinary

      - name: build with buffalo
        run: cd rpmbuild/sourceCode;buffalo build -vo CalcBuffaloBinary
                
      - name: move binary for upload
        run: cd rpmbuild/sourceCode;mv CalcBuffaloBinary /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/        
                
      - name: Commit CalcBuffaloBinary
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ${{ secrets.COMMIT_NAME }}
          author_email:  ${{ secrets.COMMIT_EMAIL }}
          message: 'Remove old and Add CalcBuffaloBinary'
          add: 'CalcBuffaloBinary'
  
#  build_tarball:
#    name: Builds .tar file
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2

#      - name: Download Buffalo Binary
#        uses: actions/download-artifact@v2
#        with:
#          name: CalcBuffaloBinary

#      - name: move CalcBuffaloBinary
#        run: mkdir buffaloBinary;mv CalcBuffaloBinary /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/buffaloBinary
      
#      - name: check if move was successful
#        run: ls buffaloBinary

#      - name: build .tar.gz
#        run: tar -czvf calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/buffaloBinary
        
#      - name: Upload calculator-1.0.tar.gz 
#        uses: actions/upload-artifact@v2
#        with:
#          name: calTarball
#          path: calculator-1.0.tar.gz    

  build_rpm:
    name: build RPM
    needs: build_with_buffalo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: RPM Build
        # You may pin to the exact commit or the version.
        # uses: naveenrajm7/rpmbuild@b52f0e593effaa08f4726afa0d0e2960131685c7
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          # path to the spec file
          spec_file: calculator.spec
      
      - name: Upload calc RPM 
        uses: actions/upload-artifact@v2
        with:
          name: calcSRPM
          path: rpmbuild/SRPMS/calculator-1.0-1.el7.src.rpm 
        
  uploads_to_copr:
    name: upload rpm to copr
    needs: build_rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download calcRPM
        uses: actions/download-artifact@v2
        with:
          name: calcSRPM
       
      - name: check for file
        run: ls 
       
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x64'  
      
      - name: Set up copr-cli
        run: pip install copr-cli

      - name: safe Copr API token to the system
        run: |
          cd ~/.config/; echo "[copr-cli]" > copr
          cd ~/.config/; echo "login = ${{ secrets.COPR_LOGIN }}" >> copr
          cd ~/.config/; echo "username = ${{ secrets.COPR_USERNAME }}" >> copr
          cd ~/.config/; echo "token = ${{ secrets.COPR_TOKEN }}" >> copr
          cd ~/.config/; echo "copr_url = https://copr.fedorainfracloud.org" >> copr
      
      - name: restart shell to use copr-cli
        run: source /etc/profile
      
      - name: Submitting a build
        run: copr-cli build  robinba/Test-Project calculator-1.0-1.el7.src.rpm
        
