# Altes Workflow File 
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: check if rpm works
        run: rpmbuild
