name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Step 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
     
      - name: get Buffalo Framwork
        run: go get -u github.com/gobuffalo/buffalo/buffalo
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x64'
      
      - name: get npm
        run: pip install npm
        
      - name: npm install
        run: npm install
              
      - name: install copr-cli
        run: pip install copr-cli

      - name: safe Copr API token to the system
        run: |
          cd ~/.config/; echo "[copr-cli]" > copr
          cd ~/.config/; echo "login = ${{ secrets.COPR_LOGIN }}" >> copr
          cd ~/.config/; echo "username = ${{ secrets.COPR_USERNAME }}" >> copr
          cd ~/.config/; echo "token = ${{ secrets.COPR_TOKEN }}" >> copr
          cd ~/.config/; echo "copr_url = https://copr.fedorainfracloud.org" >> copr
        
      - name: build with buffalo
        run: buffalo build -v -o CalcBuffaloBinary

      - name: build RPM package
        id: rpm
        uses: naveenrajm7/rpmbuild@master
        with:
          spec_file: "calculator.spec"

      - name: restart shell
        run: source /etc/profile

      - name: Submitting a build
        run: copr-cli build  robinba/Test-Project ''Hier sollte ein RPM-Packet stehen''
