name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Step 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
     
      - name: get Buffalo Framwork
        run: go get -u github.com/gobuffalo/buffalo/buffalo
      
      - name: get npm
        run: npm install
      
      - name: install copr-cli
        run: pip install copr-cli
      
      - name: build with buffalo
        run: buffalo build
  
  test:
    name: Step 2
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: download results from build
      - uses: actions/download-artifact@v2
        with:
          name: download
      
      - name: write something into a file
        run: test >> sometextfile.txt
      
      - name: read the document
        run: cat sometextfile.txt
