name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_tarball:
    name: Builds .tar file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      
      - name: build .tar.gz
        run: tar -czvf calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/
        
      - name: Upload calculator-1.0.tar.gz 
        uses: actions/upload-artifact@v2
        with:
          name: calTarball
          path: calculator-1.0.tar.gz
          
  temp_job:
    name: build RPM
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Download calculator-1.0.tar.gz
        uses: actions/download-artifact@v2
        with:
          name: calTarball
  
      - name: move file to /rpmbuild/tarball/
        run: mv calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/tarball/

      - name: check if move was successful
        run: ls /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/tarball/
        
      - name: check for directory
        run: ls /usr/bin/rpmbuild
        
      - name: Build RPM Centos7
        # You may pin to the exact commit or the version.
        # uses: Antikythera/build-rpm@b2938b8278e03cc678b6b7243dfe9b39d069711f
        uses: Antikythera/build-rpm@v1.0.2
        with:
          # list of files to be used as RPM sources, delimited by new lines
          sources: |
            rpmbuild/tarball/calculator-1.0.tar.gz
          # path to your rpm spec file
          spec_file: |
            rpmbuild/specFile/calculator.spec

