name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'

      - name: get Buffalo Framwork
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; go get -u github.com/gobuffalo/buffalo/buffalo

      - name: Set up npm
        run: pip install npm
      
      - name: remove node_module and install it again
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;rm -rf node_modules; npm install


      - name: build with buffalo
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;buffalo build -vo CalcBuffaloBinary

      - name: Create the folder tree
        run: mkdir -p /home/runner/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
           
      - name: build .tar.gz
        run: tar -czvf CalcBuffaloBinary-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/CalcBuffaloBinary      
      
      - name: Copy all the source files into SOURCES
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/; cp -R CalcBuffaloBinary-1.0.tar.gz /home/runner/rpmbuild/SOURCES

      - name: move .spec File to /SPECS
        run: mv /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/calculator.spec /home/runner/rpmbuild/SPECS
        
      - name: run rpmbuild
        run: rpmbuild -ba /home/runner/rpmbuild/SPECS/calculator.spec
      
      - name: check 
        run: ls; tree
