name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
     
    - name: get Buffalo Framwork
      run: go get -u github.com/gobuffalo/buffalo/buffalo
      
    - name: get npm
      run: npm install
      
    - name: build with buffalo
      run: buffalo build -v

    - name: search threw directories
      run: ls -trl

    - name: directorie bin
      run: cd bin; ls -trl
