name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Step 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
     
      - name: get Buffalo Framwork
        run: go get -u github.com/gobuffalo/buffalo/buffalo
      
      - name: get npm
        run: npm install

      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' 
          architecture: 'x64'
                     
      - name: check for python version
        run: python --version
              
      - name: install copr-cli
        run: pip install copr-cli
      
      - name: write something into a file
        run: cd ~/.config/; echo "[copr-cli]" > copr
      
      - name: write something into a file 2
        run:  cd ~/.config/; echo "login = oksfuomxnysozjcurjhi" >> copr
      
      - name: write something into a file 3
        run:  cd ~/.config/; echo "username = robinba" >> copr
      
      - name: write something into a file 4
        run:  cd ~/.config/; echo "token = zvfyvhhukvnhuhiepulaiadqbhzxt" >> copr      
            
      - name: write something into a file 5
        run:  cd ~/.config/; echo "copr_url = https://copr.fedorainfracloud.org" >> copr    
        
      - name: Upload these configurations
        uses: actions/upload-artifact@v2
        with:
          name: coprCLI
          path: ~/.config/copr
        
      - name: read the document
        run: cat ~/.config/copr
        
      - name : restart shell
        run: source /etc/profile
        
      - name: test if copr works 
        run: copr-cli whoami
        
      - name: build with buffalo
        run: buffalo build -o bin/CalcBuffaloBinary

      - name: search for the binary
        run: cd bin; ls -l
        
      - name: Submitting a build
        run: copr-cli build  robinba/Test-Project ~RobsCalculatorProject/bin/
