# Altes Workflow File 
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_tarball:
    name: Builds .tar file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build .tar.gz
        run: tar -czvf calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/
        
      - name: Upload calculator-1.0.tar.gz 
        uses: actions/upload-artifact@v2
        with:
          name: calTarball
          path: calculator-1.0.tar.gz
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: get Buffalo Framwork
        run: go get -u github.com/gobuffalo/buffalo/buffalo

      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'

      - name: Set up npm
        run: pip install npm

      - name: install npm
        run: npm install

      - name: build with buffalo
        run: cd /rpmbuild/sourceCode/; buffalo build -v -o CalcBuffaloBinary

  build_rpm:
    name: build RPM
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Download calculator-1.0.tar.gz
        uses: actions/download-artifact@v2
        with:
          name: calTarball
  
      - name: move file to /rpmbuild/SOURCES/
        run: mv calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/SOURCES/

      - name: check if move was successful
        run: ls /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/SOURCES/
        
      - name: check for .spec file
        run: ls /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/
        
      - name: check for path
        run: pwd
        
      - name: RPM Build
        # You may pin to the exact commit or the version.
        # uses: naveenrajm7/rpmbuild@b52f0e593effaa08f4726afa0d0e2960131685c7
        id: rpm
        uses: naveenrajm7/rpmbuild@v1.0.0
        with:
          # path to the spec file
          spec_file: calculator.spec
        
      - name: check for new builds
        run: ls
