name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
                   
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'

      - name: get Buffalo Framwork
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; go get -u github.com/gobuffalo/buffalo/buffalo

      - name: Set up npm
        run: pip install npm
      
      - name: remove node_module and install it again
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;rm -rf node_modules; npm install

      - name: build with buffalo
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;buffalo build -vo CalcBuffaloBinary

      - name: Create the folder tree
        run: mkdir -p /home/runner/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
           
      - name: build .tar.gz
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/; tar -czvf CalcBuffaloBinary-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/CalcBuffaloBinary  

      - name: Upload artifact CalcBuffaloBinary-1.0.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: CalcBuffaloBinary-1.0.tar.gz
          path: /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/CalcBuffaloBinary-1.0.tar.gz  

      - name: check for files
        run: ls /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode
      
      - name: Copy all the source files into SOURCES
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; cp -R CalcBuffaloBinary-1.0.tar.gz /home/runner/rpmbuild/SOURCES

      - name: see if file moved
        run: ls /home/runner/rpmbuild/SOURCES

      - name: move .spec File to /SPECS
        run: mv /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/calculator.spec /home/runner/rpmbuild/SPECS
        
      - name: build RPM
        run: rpmbuild -bb /home/runner/rpmbuild/SPECS/calculator.spec        

      - name: Upload artifact RPM
        uses: actions/upload-artifact@v2
        with:
          name: RPM
          path: /home/runner/rpmbuild/RPMS/x86_64

      - name: build SRPM
        run: rpmbuild -bs /home/runner/rpmbuild/SPECS/calculator.spec        
            
      - name: Upload artifact SRPM
        uses: actions/upload-artifact@v2
        with:
          name: SRPM
          path: /home/runner/rpmbuild/SRPMS/calculator-1.0-1.src.rpm          
            
      - name: Set up copr-cli
        run: pip install copr-cli

      - name: safe Copr API token to the system
        run: |
          cd ~/.config/; echo "[copr-cli]" > copr
          cd ~/.config/; echo "login = ${{ secrets.COPR_LOGIN }}" >> copr
          cd ~/.config/; echo "username = ${{ secrets.COPR_USERNAME }}" >> copr
          cd ~/.config/; echo "token = ${{ secrets.COPR_TOKEN }}" >> copr
          cd ~/.config/; echo "copr_url = https://copr.fedorainfracloud.org" >> copr
      
      - name: restart shell to use copr-cli
        run: source /etc/profile  
    
      - name: Submitting a build
        run: copr-cli build  robinba/Test-Project /home/runner/rpmbuild/SRPMS/calculator-1.0-1.src.rpm
        
  release-files:
    name: Release files to GitHub Releases
    runs-on: ubuntu-latest
    needs: [checkout_rpm]
    steps:
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
      
      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: CalcBuffaloBinary-1.0.tar.gz      
      
      - name: upload asset to GitHub Release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./CalcBuffaloBinary-1.0.tar.gz
          asset_name: CalcBuffaloBinary-v${{ github.run_number }}
          asset_content_type: application/zip

      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: SRPM

      - name: upload asset to GitHub Release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./calculator-1.0-1.src.rpm
          asset_name: SRPM-v${{ github.run_number }}
          asset_content_type: application/zip

      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: RPM
          
      - name: upload asset to GitHub Release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./calculator-1.0-1.x86_64.rpm
          asset_name: RPM-v${{ github.run_number }}
          asset_content_type: application/octet-stream
