name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'

      - name: get Buffalo Framwork
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; go get -u github.com/gobuffalo/buffalo/buffalo

      - name: Set up npm
        run: pip install npm
      
      - name: remove node_module and install it again
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;rm -rf node_modules; npm install

      - name: build with buffalo
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;buffalo build -vo CalcBuffaloBinary

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./CalcBuffaloBinary
          asset_name: CalcBuffaloBinary
          asset_content_type: CalcBuffaloBinary/binary

      - name: Create the folder tree
        run: mkdir -p /home/runner/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
           
      - name: build .tar.gz
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/; tar -czvf CalcBuffaloBinary-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/CalcBuffaloBinary 
      
      - name: check for files
        run: ls /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode
      
      - name: Copy all the source files into SOURCES
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; cp -R CalcBuffaloBinary-1.0.tar.gz /home/runner/rpmbuild/SOURCES

      - name: see if file moved
        run: ls /home/runner/rpmbuild/SOURCES

      - name: move .spec File to /SPECS
        run: mv /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/calculator.spec /home/runner/rpmbuild/SPECS
        
      - name: build RPM
        run: rpmbuild -bb /home/runner/rpmbuild/SPECS/calculator.spec        

      - name: build SRPM
        run: rpmbuild -bs /home/runner/rpmbuild/SPECS/calculator.spec        
            
      - name: Set up copr-cli
        run: pip install copr-cli

      - name: safe Copr API token to the system
        run: |
          cd ~/.config/; echo "[copr-cli]" > copr
          cd ~/.config/; echo "login = ${{ secrets.COPR_LOGIN }}" >> copr
          cd ~/.config/; echo "username = ${{ secrets.COPR_USERNAME }}" >> copr
          cd ~/.config/; echo "token = ${{ secrets.COPR_TOKEN }}" >> copr
          cd ~/.config/; echo "copr_url = https://copr.fedorainfracloud.org" >> copr
      
      - name: restart shell to use copr-cli
        run: source /etc/profile
      
      - name: Submitting a build
        run: copr-cli build  robinba/Test-Project /home/runner/rpmbuild/SRPMS/calculator-1.0-1.src.rpm
