name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_tarball:
    name: Builds .tar file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: build .tar.gz
        run: tar -czvf calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode/
        
      - name: Upload calculator-1.0.tar.gz 
        uses: actions/upload-artifact@v2
        with:
          name: calTarball
          path: calculator-1.0.tar.gz
          
  temp_job:
    name: build RPM
    needs: build_tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Download calculator-1.0.tar.gz
        uses: actions/download-artifact@v2
        with:
          name: calTarball
  
      - name: move file to /rpmbuild/tarball/
        run: mv calculator-1.0.tar.gz /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/tarball/

      - name: check if move was successful
        run: ls /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/tarball/
      
      - name: create rpm tree and check
        run: | 
          cd /home/runner 
          mkdir rpmbuild
          cd rpmbuild
          mkdir BUILD
          mkdir RPMS
          mkdir SOURCES
          mkdir SPECS
          mkdir SRPMS
          pwd
          ls
          
          
      - name: loganbickmore/rpmbuild
        # You may pin to the exact commit or the version.
        # uses: loganbickmore/rpmbuild@897c4539291e2905dec831e5155a9ea2b8208be5
        uses: loganbickmore/rpmbuild@v1.0.0
        with:
          # path to spec file
          spec_file: /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/specFile/calculator.spec
          # path to source archive file
          src_archive: /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/tarball/calculator-1.0.tar.gz
        continue-on-error: true  
          
      - name: /usr/bin/rpmbuild afterwards?
        run: cd /usr/bin; ls
