# Altes Workflow File 
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: check if rpm works
        run: rpmbuild --help

      - name: Create the folder tree
        run: mkdir -p ~/rpmbuild/{SPECS,SOURCES,BUILD,BUILDROOT,RPMS,SRPMS}
      
      - name: check for path
        run: pwd
      
      - name: Copy all the source files into
        run: cp -r /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode ~/rpmbuild/SOURCES

      - name: check for copie
        run: ls ~/rpmbuild/SOURCES
