name: Knowhow Sharing Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout_rpm:
    name: chechout Rpm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
                   
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - uses: actions/setup-python@v2
        with:
            python-version: '3.7' 
            architecture: 'x64'

      - name: get Buffalo Framwork
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode; go get -u github.com/gobuffalo/buffalo/buffalo

      - name: Set up npm
        run: pip install npm
      
      - name: remove node_module and install it again
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;rm -rf node_modules; npm install

      - name: build with buffalo
        run: cd /home/runner/work/RobsCalculatorProject/RobsCalculatorProject/rpmbuild/sourceCode;buffalo build -vo CalcBuffaloBinary
